-- Generated from src/data/catalog.json — re-run scripts/generate-seed-sql.js if the ratecard changes.

insert into inventory_items (sku_id, category, product_name, grammage_g, mrp_inr, shelf_life_days, current_stock, active, tier) values
  ('ragi-chips-peri-peri', 'Ragi Chips', 'Peri Peri Ragi Chips', 57, 50, 120, 0, true, 'yellow'),
  ('ragi-chips-chatpata-crunch', 'Ragi Chips', 'Chatpata Crunch Ragi Chips', 57, 50, 120, 0, true, 'yellow'),
  ('ragi-chips-jalapeno', 'Ragi Chips', 'Jalapeno Ragi Chips', 57, 50, 120, 0, true, 'yellow'),
  ('quinoa-puffs-sriracha', 'Quinoa Puffs', 'Sriracha Quinoa Puffs', 35, 60, 90, 0, true, 'yellow'),
  ('quinoa-puffs-flaming-hot-cheese', 'Quinoa Puffs', 'Flaming Hot Cheese Quinoa Puffs', 38, 40, 90, 0, true, 'yellow'),
  ('quinoa-puffs-tangy-tomato', 'Quinoa Puffs', 'Tangy Tomato Quinoa Puffs', 35, 60, 90, 0, true, 'yellow'),
  ('quinoa-puffs-dahi-papdi-chaat', 'Quinoa Puffs', 'Dahi Papdi Chaat Quinoa Puffs', 35, 60, 90, 0, true, 'yellow'),
  ('jowar-puffs-desi-masala', 'Jowar Puffs', 'Desi Masala Jowar Puffs', 38, 40, 90, 0, true, 'yellow'),
  ('jowar-puffs-nacho-cheese', 'Jowar Puffs', 'Nacho Cheese Jowar Puffs', 35, 40, 90, 0, true, 'yellow'),
  ('jowar-puffs-cream-onion', 'Jowar Puffs', 'Cream & Onion Jowar Puffs', 35, 40, 90, 0, true, 'yellow'),
  ('jowar-puffs-korean-bbq', 'Jowar Puffs', 'Korean BBQ Jowar Puffs', 100, 115, 90, 0, true, 'yellow'),
  ('khakra-cheese-dosa', 'Khakra', 'Cheese Dosa Khakra', 50, 60, 120, 0, true, 'yellow'),
  ('khakra-tomato-dosa', 'Khakra', 'Tomato Dosa Khakra', 50, 60, 120, 0, true, 'yellow'),
  ('khakra-thai-chilli-coin', 'Khakra', 'Thai Chilli Coin Khakra', 50, 70, 120, 0, true, 'yellow'),
  ('millet-fingers-cheddar-cheese', 'Millet Fingers', 'Cheddar Cheese Millet Fingers', 40, 45, 120, 0, true, 'yellow'),
  ('millet-fingers-chatpata-masala', 'Millet Fingers', 'Chatpata Masala Millet Fingers', 40, 45, 90, 0, true, 'yellow'),
  ('multigrain-chips-sour-cream-onion', 'Multigrain Chips', 'Sour Cream & Onion Multigrain Chips', 40, 45, 120, 0, true, 'yellow'),
  ('multigrain-chips-smoky-bbq', 'Multigrain Chips', 'Smoky Bbq Multigrain Chips', 45, 50, 120, 0, true, 'yellow'),
  ('multigrain-chips-cheese-herbs', 'Multigrain Chips', 'Cheese & Herbs Multigrain Chips', 40, 45, 120, 0, true, 'yellow'),
  ('jowar-chips-cheddar-cheese', 'Jowar Chips', 'Cheddar Cheese Jowar Chips', 55, 50, 120, 0, true, 'yellow'),
  ('jowar-chips-sweet-chilli', 'Jowar Chips', 'Sweet Chilli Jowar Chips', 55, 50, 120, 0, true, 'yellow'),
  ('jowar-chips-chatpata-masala', 'Jowar Chips', 'Chatpata Masala Jowar Chips', 55, 50, 120, 0, true, 'yellow'),
  ('crunchies-lemon-chilli-baked', 'Crunchies', 'Lemon Chilli Baked Crunchies', 40, 50, 270, 0, true, 'yellow'),
  ('crunchies-masala-baked', 'Crunchies', 'Masala Baked Crunchies', 40, 50, 270, 0, true, 'yellow'),
  ('protein-snacks-pudina-bhujia', 'Protein Snacks', 'Protein Pudina Bhujia', 60, 60, 270, 0, true, 'yellow'),
  ('protein-snacks-masala-bhujia', 'Protein Snacks', 'Protein Masala Bhujia', 60, 60, 270, 0, true, 'yellow'),
  ('protein-snacks-thai-chilli-popped', 'Protein Snacks', 'Thai Chilli Protein Popped Chips', 30, 60, 180, 0, true, 'yellow'),
  ('protein-snacks-pani-puri-popped', 'Protein Snacks', 'Pani Puri Protein Popped Chips', 30, 60, 180, 0, true, 'yellow'),
  ('popped-chips-korean-bbq-chickpea', 'Popped Chips', 'Korean BBQ Chickpea Popped Chips', 30, 55, 180, 0, true, 'yellow'),
  ('popped-chips-garlic-bread-chickpea', 'Popped Chips', 'Garlic Bread Chickpea Popped Chips', 30, 50, 180, 0, true, 'yellow'),
  ('popped-chips-truffle-chickpea', 'Popped Chips', 'Truffle Chickpea Popped Chips', 30, 60, 180, 0, true, 'yellow'),
  ('popped-chips-himalayan-pink-salt-pepper', 'Popped Chips', 'Himalayan Pink Salt & Pepper Popped Chips', 30, 50, 90, 0, true, 'yellow'),
  ('popped-chips-thai-chilli-quinoa-chia', 'Popped Chips', 'Thai Chilli Quinoa Chia Popped Chips', 30, 50, 90, 0, true, 'yellow'),
  ('ragi-sticks-spicy-garlic', 'Ragi Sticks', 'Spicy Garlic Ragi Sticks', 40, 45, 120, 0, true, 'yellow'),
  ('ragi-sticks-achari-masala', 'Ragi Sticks', 'Achari Masala Ragi Sticks', 40, 45, 120, 0, true, 'yellow'),
  ('chickpea-puffs-lime-sriracha', 'Chickpea Puffs', 'Lime & Sriracha Chickpea Puffs', 35, 50, 90, 0, true, 'yellow'),
  ('chickpea-puffs-tangy-tomato', 'Chickpea Puffs', 'Tangy Tomato Chickpea Puffs', 35, 50, 90, 0, true, 'yellow'),
  ('chickpea-puffs-herb-cheese', 'Chickpea Puffs', 'Herb & Cheese Chickpea Puffs', 35, 50, 90, 0, true, 'yellow'),
  ('indian-snacks-salted-banana-chips', 'Indian Snacks', 'Salted Banana Chips', 72, 60, 180, 0, true, 'yellow'),
  ('indian-snacks-baked-mini-samosas', 'Indian Snacks', 'Baked Mini Samosas', 50, 60, 90, 0, true, 'yellow'),
  ('makhanas-pudina', 'Makhanas', 'Pudina Makhana', 30, 115, 90, 0, true, 'yellow'),
  ('makhanas-cheddar-cheese', 'Makhanas', 'Cheddar Cheese Makhana', 30, 115, 90, 0, true, 'yellow'),
  ('makhanas-bombay-chaat', 'Makhanas', 'Bombay Chaat Makhana', 30, 115, 90, 0, true, 'yellow'),
  ('veggie-chips-roasted-makki', 'Veggie Chips', 'Roasted Makki Chips', 75, 50, 120, 0, true, 'yellow'),
  ('veggie-chips-chatpata-crispy-sweet-corn', 'Veggie Chips', 'Chatpata Crispy Sweet Corn', 45, 100, 180, 0, true, 'yellow'),
  ('chikkis-peanut', 'Chikkis', 'Peanut Chikki', 75, 70, 180, 0, true, 'yellow'),
  ('chikkis-vanilla-seeds', 'Chikkis', 'Vanilla & Seeds Chikki', 75, 70, 180, 0, true, 'yellow'),
  ('chikkis-coconut', 'Chikkis', 'Coconut Chikki', 75, 70, 180, 0, true, 'yellow'),
  ('peanuts-truffle', 'Peanuts', 'Truffle Peanuts', 40, 35, 90, 0, true, 'yellow'),
  ('peanuts-korean-bbq', 'Peanuts', 'Korean BBQ Peanuts', 40, 35, 90, 0, true, 'yellow'),
  ('peanuts-himalayan-pink-salt', 'Peanuts', 'Himalayan Pink Salt Peanuts', 40, 35, 90, 0, true, 'yellow'),
  ('sweet-dipsters-pistachio', 'Sweet Dipsters', 'Pistachio Dip with Biscuit Sticks', 44, 60, 135, 0, true, 'yellow'),
  ('sweet-dipsters-hazelnut', 'Sweet Dipsters', 'Hazelnut Dip with Biscuit Sticks', 44, 60, 135, 0, true, 'yellow'),
  ('sweet-dipsters-chocolatey', 'Sweet Dipsters', 'Chocolatey Dip with Biscuit Sticks', 34, 35, 135, 0, true, 'yellow'),
  ('sweet-dipsters-caramel', 'Sweet Dipsters', 'Caramel Dip with Biscuit Sticks', 34, 35, 135, 0, true, 'yellow'),
  ('sweet-dipsters-vanilla-creme', 'Sweet Dipsters', 'Vanilla Creme Dip with Biscuit Sticks', 34, 35, 135, 0, true, 'yellow'),
  ('large-dipsters-spicy-mayo-jalapeno-ragi', 'Large Dipsters', 'Spicy Mayo Dip with Jalapeño Ragi Chips', 60, 50, 135, 0, true, 'yellow'),
  ('large-dipsters-cheesy-jalapeno-piri-piri-ragi', 'Large Dipsters', 'Cheesy Jalapeño Dip with Piri Piri Ragi Chips', 60, 50, 135, 0, true, 'yellow'),
  ('baked-pizza-sticks-cheesy-jalapeno-dip', 'Baked Pizza Sticks', 'Baked Pizza Sticks with a Cheesy Jalapeno Dip', 75, 70, 90, 0, true, 'yellow'),
  ('cookies-almond', 'Cookies', 'Almond Cookies', 70, 85, 180, 0, true, 'yellow'),
  ('cookies-coffee', 'Cookies', 'Coffee Cookies', 70, 85, 180, 0, true, 'yellow'),
  ('cookies-choco-chunk', 'Cookies', 'Choco Chunk Cookies', 50, 99, 180, 0, true, 'yellow'),
  ('cookies-choco-filled-center-filled', 'Cookies', 'Choco Filled Cookies / Center Filled Cookies', 80, 115, 300, 0, true, 'yellow'),
  ('cookies-ginger-snap', 'Cookies', 'Ginger Snap Cookies', 70, 85, 180, 0, true, 'yellow'),
  ('cookies-dark-chocolate-beetroot', 'Cookies', 'Dark Chocolate & Beetroot Cookies', 70, 85, 180, 0, true, 'yellow'),
  ('healthy-spreads-salted-caramel', 'Healthy Spreads', 'Salted Caramel Spread', 250, 250, 270, 0, true, 'yellow'),
  ('healthy-spreads-pistachio', 'Healthy Spreads', 'Pistachio Spread', 250, 450, 270, 0, true, 'yellow'),
  ('healthy-spreads-chocolate', 'Healthy Spreads', 'Chocolate Spread', 250, 245, 270, 0, true, 'yellow'),
  ('healthy-spreads-vanilla-creme', 'Healthy Spreads', 'Vanilla Creme Spread', 250, 245, 270, 0, true, 'yellow'),
  ('healthy-spreads-hazelnut', 'Healthy Spreads', 'Hazelnut Spread', 250, 285, 270, 0, true, 'yellow'),
  ('hot-chocolate-mix', 'Hot Chocolate Mix', 'Hot Chocolate Mix', 120, 130, 270, 0, true, 'yellow'),
  ('kunafa-chocolate-bites-box-of-4', 'Kunafa', 'Kunafa Chocolate Bites - Box Of 4', 56, 210, 180, 0, true, 'yellow'),
  ('kunafa-chocolate-bites-box-of-6', 'Kunafa', 'Kunafa Chocolate Bites - Box Of 6', 84, 335, 180, 0, true, 'yellow')
on conflict (sku_id) do nothing;

insert into b2b_accounts (account_id, company_name, contact_name, contact_email, contact_phone, pricing_tier_id) values
  ('acct-blue-orchard', 'Blue Orchard Mart', 'Rahul Mehta', 'rahul@blueorchardmart.example', '+91 98200 11223', null),
  ('acct-corner-cafe', 'Corner Cafe Collective', 'Ayesha Khan', 'ayesha@cornercafe.example', '+91 98100 44556', null)
on conflict (account_id) do nothing;
